import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {NavBar} from "@/components/nav-bar";
import {getAuthenticatedSession} from "@/auth/auth-server-helpers";
import {repository} from "@/db/repository";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

async function getChats() {
    const session = await getAuthenticatedSession();

    if(!session) {
        return [];
    }

    return repository.getChats(session.user.id);
}

export default async function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    const chats = await getChats();
    return (
        <html lang="en" className="dark">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <NavBar/>
        <main className="max-w-7xl mx-auto pt-12 pb-4 px-2 md:px-6 relative size-full h-screen">
            {children}
        </main>
        </body>
        </html>
    );
}
