import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {AppHeader} from "@/components/layout/app-header";
import {SidebarProvider} from "@/components/ui/sidebar";
import {AppSideBar} from "@/components/layout/app-side-bar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <SidebarProvider>
                    <AppHeader/>
                    <AppSideBar/>
                    <main className="max-w-7xl mx-auto pt-12 pb-4 px-2 md:px-6 relative size-full h-screen">
                        {children}
                    </main>
                </SidebarProvider>
            </body>
        </html>
    );
}
